<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>dwl</string>
	</array>
	<key>name</key>
	<string>DataWeave</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#imports</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#dw-directive</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#statements</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>case-clause</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;!\.|\$)\b(case|else(?=\s*-&gt;))\b(?!\$|\.)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.switch.dw</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\-\&gt;</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.switch.dw</string>
				</dict>
			</dict>
			<key>name</key>
			<string>case-clause.expr.dw</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?&lt;!\.|\$)\b(is)\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.as.dw</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\-\&gt;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#types</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#expressions</string>
				</dict>
			</array>
		</dict>
		<key>classes</key>
		<dict>
			<key>begin</key>
			<string>(?=\s*(?:companion|class|object|interface))</string>
			<key>end</key>
			<string>}|(?=$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b(companion\s*)?(class|object|interface)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.dw</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=&lt;|{|\(|:)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\b(object)\b</string>
							<key>name</key>
							<string>keyword.other.dw</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\w+</string>
							<key>name</key>
							<string>entity.name.type.class.dw</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>&lt;</string>
					<key>end</key>
					<string>&gt;</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#generics</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\(</string>
					<key>end</key>
					<string>\)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#parameters</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(:)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.declaration.dw</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?={|$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\w+</string>
							<key>name</key>
							<string>entity.other.inherited-class.dw</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>\(</string>
							<key>end</key>
							<string>\)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#expressions</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\{</string>
					<key>end</key>
					<string>\}</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#statements</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.dw</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.dw</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>comment.line.double-slash.dw</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.dw</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\s*((//).*$\n?)</string>
				</dict>
			</array>
		</dict>
		<key>constants</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(true|false|null)\b</string>
					<key>name</key>
					<string>constant.language.dw</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)([LlFfUuDd]|UL|ul)?\b</string>
					<key>name</key>
					<string>constant.numeric.dw</string>
				</dict>
			</array>
		</dict>
		<key>dw-directive</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;!\.|\$)(%dw)\s+([0-9]\.[0-9])(?!\$|\.)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.dw</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>comment.dw</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=\n)</string>
			<key>name</key>
			<string>meta.directive.ns.dw</string>
		</dict>
		<key>expressions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#paren-expression</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#match-statement</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#object-literal</string>
				</dict>
			</array>
		</dict>
		<key>functions</key>
		<dict>
			<key>begin</key>
			<string>(?=\s*(?:fun))</string>
			<key>end</key>
			<string>}|(?=$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b(fun)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.dw</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\()</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>entity.name.function.dw</string>
								</dict>
							</dict>
							<key>match</key>
							<string>([\.&lt;\?&gt;\w]+\.)?(\w+)</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>&lt;</string>
							<key>end</key>
							<string>&gt;</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#generics</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\(</string>
					<key>end</key>
					<string>\)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#parameters</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(:)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.declaration.dw</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?==)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#types</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(=)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.assignment.dw</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#expressions</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>generics</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(:)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.declaration.dw</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=,|&gt;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#types</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>&lt;:</string>
					<key>name</key>
					<string>keyword.operator.extends.dw</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywords</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\w+</string>
					<key>name</key>
					<string>storage.type.generic.dw</string>
				</dict>
			</array>
		</dict>
		<key>imports</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.dw</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other.dw</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(import)\s+[^ $]+\s+(from)?</string>
				</dict>
			</array>
		</dict>
		<key>input-directive</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;!\.|\$)\b(input)\s+([[:alpha:]][[:alnum:]]*)\s+([^\n]*)(?!\$|\.)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.ns.dw</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.ns.dw</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>meta.definition.ns.dw string.mime.dw</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=\n)</string>
			<key>name</key>
			<string>meta.directive.ns.dw</string>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(var|val|public|private|protected|abstract|final|enum|open|attribute|annotation|override|inline|var|val|vararg|lazy|in|out|internal|data|tailrec|operator|infix|const|yield|typealias|typeof)\b</string>
					<key>name</key>
					<string>storage.modifier.dw</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(try|catch|finally|throw)\b</string>
					<key>name</key>
					<string>keyword.control.catch-exception.dw</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(if|else|while|for|do|return|when|where|break|continue)\b</string>
					<key>name</key>
					<string>keyword.control.dw</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&lt;!\.|\$)\b(as|is)\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.as.dw</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=$|^|[;,:})\]])</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#types</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>(==|!=|===|!==|&lt;=|&gt;=|&lt;|&gt;)</string>
					<key>name</key>
					<string>keyword.operator.comparison.dw</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(=)</string>
					<key>name</key>
					<string>keyword.operator.assignment.dw</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(:)</string>
					<key>name</key>
					<string>keyword.operator.declaration.dw</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\.)</string>
					<key>name</key>
					<string>keyword.operator.dot.dw</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\-\-|\+\+)</string>
					<key>name</key>
					<string>keyword.operator.increment-decrement.dw</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\-|\+|\*|\/|%)</string>
					<key>name</key>
					<string>keyword.operator.arithmetic.dw</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\+=|\-=|\*=|\/=)</string>
					<key>name</key>
					<string>keyword.operator.arithmetic.assign.dw</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(not|and|or)\b</string>
					<key>name</key>
					<string>keyword.operator.logical.dw</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\.\.)</string>
					<key>name</key>
					<string>keyword.operator.range.dw</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(;)</string>
					<key>name</key>
					<string>punctuation.terminator.dw</string>
				</dict>
			</array>
		</dict>
		<key>match-block</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.switch.dw</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=\})</string>
			<key>name</key>
			<string>match-block.expr.dw</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#case-clause</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#expressions</string>
				</dict>
			</array>
		</dict>
		<key>match-statement</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;!\.|\$)\b(match\s*)(?=\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.switch.dw</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.switch.dw</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.block.dw</string>
				</dict>
			</dict>
			<key>name</key>
			<string>match-statement.expr.dw</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#match-block</string>
				</dict>
			</array>
		</dict>
		<key>ns-directive</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;!\.|\$)\b(ns)\s+([[:alpha:]][[:alnum:]]*)\s+([^\n]*)(?!\$|\.)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.ns.dw</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.ns.dw</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>meta.definition.ns.dw string.url.dw</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=\n)</string>
			<key>name</key>
			<string>meta.directive.ns.dw</string>
		</dict>
		<key>object-literal</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.block.dw</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.block.dw</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.objectliteral.dw</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#object-member</string>
				</dict>
			</array>
		</dict>
		<key>object-member</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#paren-expression</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?=[\'\"])</string>
					<key>end</key>
					<string>(?=:)</string>
					<key>name</key>
					<string>meta.object.member.dw meta.object-literal.key.dw</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#strings</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>entity.name.ns.dw</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b([[:alpha:]][[:alnum:]]+#)</string>
					<key>name</key>
					<string>meta.object.member.dw</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.object-literal.key.dw</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.decimal.dw</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?![_$[:alpha:]])([[:digit:]]+)\s*(?=:)</string>
					<key>name</key>
					<string>meta.object.member.dw</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.object-literal.key.dw</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=,|\})</string>
					<key>match</key>
					<string>(?:[_$[:alpha:]][_$[:alnum:]]*)\s*(?=:)</string>
					<key>name</key>
					<string>meta.object.member.dw</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#object-member-body</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#punctuation-comma</string>
				</dict>
			</array>
		</dict>
		<key>object-member-body</key>
		<dict>
			<key>begin</key>
			<string>:</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.object-literal.key.dw punctuation.separator.key-value.dw</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=,|\})</string>
			<key>name</key>
			<string>meta.object.member.dw</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#expressions</string>
				</dict>
			</array>
		</dict>
		<key>output-directive</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;!\.|\$)\b(output)\s+([[:alpha:]][[:alnum:]]*)(?!\$|\.)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.ns.dw</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.definition.ns.dw variable.other.ns.dw</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=\n)</string>
			<key>name</key>
			<string>meta.directive.ns.dw</string>
		</dict>
		<key>parameters</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(:)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.declaration.dw</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=,|\)|=)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#types</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(=)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.declaration.dw</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=,|\))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#expressions</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywords</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\w+</string>
					<key>name</key>
					<string>variable.parameter.function.dw</string>
				</dict>
			</array>
		</dict>
		<key>paren-expression</key>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#expressions</string>
				</dict>
			</array>
		</dict>
		<key>statements</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#namespaces</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#typedefs</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variables</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#ns-directive</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#input-directive</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#output-directive</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#expressions</string>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.dw</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.dw</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.dw</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#template-substitution-element</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>constant.character.escape.dw</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.dw</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.dw</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.dw</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#template-substitution-element</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>constant.character.escape.dw</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>`</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.dw</string>
						</dict>
					</dict>
					<key>end</key>
					<string>`</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.dw</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.dw</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#template-substitution-element</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>constant.character.escape.dw</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>template-substitution-element</key>
		<dict>
			<key>begin</key>
			<string>\$\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.other.dw</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.other.dw</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.template.expression.dw</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#expressions</string>
				</dict>
			</array>
		</dict>
		<key>typedefs</key>
		<dict>
			<key>begin</key>
			<string>(?=\s*(?:type))</string>
			<key>end</key>
			<string>(?=$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(type)\b</string>
					<key>name</key>
					<string>keyword.other.dw</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>&lt;</string>
					<key>end</key>
					<string>&gt;</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#generics</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>=</string>
					<key>name</key>
					<string>keyword.other.dw</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#types</string>
				</dict>
			</array>
		</dict>
		<key>types</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(String|Boolean|Number|Range|Namespace|Uri|DateTime|LocalDateTime|Date|LocalTime|Time|TimeZone|Period|Binary|Null|Regex|Nothing|Any|Object|Key)\b</string>
					<key>name</key>
					<string>storage.type.buildin.dw</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\b(Array|Type)&lt;\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.buildin.collection.dw</string>
						</dict>
					</dict>
					<key>end</key>
					<string>&gt;</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#types</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>\b([A-Z][a-zA-Z0-9_]*)</string>
					<key>name</key>
					<string>storage.type.dw</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\w+&lt;</string>
					<key>end</key>
					<string>&gt;</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#types</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#keywords</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\(</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.tuple.dw</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\)\s*=&gt;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#parameters</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\{</string>
					<key>end</key>
					<string>\}</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#statements</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\(</string>
					<key>end</key>
					<string>\)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#types</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>(&amp;)</string>
					<key>name</key>
					<string>keyword.operator.declaration.dw</string>
				</dict>
			</array>
		</dict>
		<key>variables</key>
		<dict>
			<key>begin</key>
			<string>(?=\s*(?:var))</string>
			<key>end</key>
			<string>(?=:|=|$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b(var)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.dw</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=:|=|$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>&lt;</string>
							<key>end</key>
							<string>&gt;</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#generics</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>entity.name.variable.dw</string>
								</dict>
							</dict>
							<key>match</key>
							<string>([\.&lt;\?&gt;\w]+\.)?(\w+)</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(:)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.declaration.dw</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?==|$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#types</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(=)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.assignment.dw</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#expressions</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.dw</string>
	<key>uuid</key>
	<string>d508c059-a938-4779-b2bc-ff43a5098907</string>
</dict>
</plist>
